#!/bin/sh
remote=$1
while read local_ref local_sha remote_ref remote_sha; do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "error: direct pushes to main are not allowed. open a PR instead."
    exit 1
  fi
done
