// Shared fixture for WhatsWorkingPanel tests: one representative MarketingInsightsResponse.

import type { MarketingInsightsResponse } from './types'

export function insightsResponse(overrides: Partial<MarketingInsightsResponse> = {}): MarketingInsightsResponse {
  return {
    window: { from: '2026-08-17T00:00:00Z', to: '2026-09-16T00:00:00Z', days: 30 },
    totals: {
      key: 'all',
      posts: 12,
      views: 48000,
      likes: 3200,
      comments: 410,
      shares: 190,
      saves: 260,
      engagementRate: 0.0846,
      medianViews: 3100,
      avgViewPct: null,
    },
    byPlatform: [
      {
        key: 'instagram',
        label: 'Instagram',
        posts: 7,
        views: 30000,
        likes: 2200,
        comments: 300,
        shares: 120,
        saves: 200,
        engagementRate: 0.094,
        medianViews: 3400,
        avgViewPct: null,
      },
      {
        key: 'tiktok',
        label: 'TikTok',
        posts: 5,
        views: 18000,
        likes: 1000,
        comments: 110,
        shares: 70,
        saves: 60,
        engagementRate: 0.069,
        medianViews: 2800,
        avgViewPct: null,
      },
    ],
    byFormat: [
      {
        key: 'REEL',
        posts: 8,
        views: 34000,
        likes: 2500,
        comments: 320,
        shares: 150,
        saves: 210,
        engagementRate: 0.09,
        medianViews: 3300,
        avgViewPct: null,
      },
      {
        key: 'FEED',
        posts: 4,
        views: 14000,
        likes: 700,
        comments: 90,
        shares: 40,
        saves: 50,
        engagementRate: 0.06,
        medianViews: 2600,
        avgViewPct: null,
      },
    ],
    byHour: [
      { key: '9', posts: 4, views: 12000, likes: 900, comments: 100, shares: 40, saves: 60, engagementRate: 0.09, medianViews: null, avgViewPct: null },
      { key: '18', posts: 8, views: 36000, likes: 2300, comments: 310, shares: 150, saves: 200, engagementRate: 0.083, medianViews: null, avgViewPct: null },
    ],
    byWeekday: [
      { key: 'MONDAY', posts: 3, views: 9000, likes: 600, comments: 80, shares: 30, saves: 40, engagementRate: 0.083, medianViews: null, avgViewPct: null },
      { key: 'FRIDAY', posts: 5, views: 20000, likes: 1400, comments: 180, shares: 90, saves: 110, engagementRate: 0.089, medianViews: null, avgViewPct: null },
    ],
    topPosts: [
      {
        workItemId: 'wi-1',
        displayId: 'MK-101',
        title: 'Launch teaser',
        workflowSlug: 'MARKETING',
        captionExcerpt: 'Big things are coming this fall — stay tuned for the drop.',
        targetId: 'tgt-1',
        platform: 'instagram',
        format: 'REEL',
        accountLabel: '@brand',
        permalink: 'https://instagram.com/p/abc',
        firedAt: '2026-09-10T18:00:00Z',
        views: 15000,
        likes: 1200,
        comments: 150,
        shares: 80,
        saves: 110,
        engagementRate: 0.103,
        avgViewPct: null,
        observedAt: '2026-09-12T00:00:00Z',
      },
    ],
    bottomPosts: [
      {
        workItemId: 'wi-2',
        displayId: 'MK-88',
        title: 'Behind the scenes',
        workflowSlug: null,
        captionExcerpt: null,
        targetId: 'tgt-2',
        platform: 'tiktok',
        format: 'FEED',
        accountLabel: null,
        permalink: null,
        firedAt: '2026-08-20T09:00:00Z',
        views: 1200,
        likes: 10,
        comments: 1,
        shares: 0,
        saves: 0,
        engagementRate: 0.009,
        avgViewPct: null,
        observedAt: '2026-08-21T00:00:00Z',
      },
    ],
    movers: [
      { metric: 'posts', current: 12, previous: 9, deltaPct: 33.3 },
      { metric: 'views', current: 48000, previous: 51000, deltaPct: -5.9 },
      { metric: 'engagementRate', current: 0.0846, previous: 0.07, deltaPct: 20.9 },
    ],
    coverage: {
      platforms: ['instagram', 'tiktok'],
      notes: ["Facebook doesn't report views; connect it under Integrations to include it here."],
    },
    ...overrides,
  }
}

export function emptyInsightsResponse(): MarketingInsightsResponse {
  return insightsResponse({
    totals: {
      key: 'all',
      posts: 0,
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      saves: 0,
      engagementRate: null,
      medianViews: null,
      avgViewPct: null,
    },
    byPlatform: [],
    byFormat: [],
    byHour: [],
    byWeekday: [],
    topPosts: [],
    bottomPosts: [],
    movers: [],
    coverage: { platforms: [], notes: [] },
  })
}
