ALTER TYPE issue_status ADD VALUE IF NOT EXISTS 'READY_FOR_DEVELOPMENT';
ALTER TYPE issue_status ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE issue_status ADD VALUE IF NOT EXISTS 'CODE_REVIEW';
ALTER TYPE issue_status ADD VALUE IF NOT EXISTS 'DONE';
ALTER TYPE issue_status ADD VALUE IF NOT EXISTS 'CLOSED';
