name: Deploy on label

on:
  pull_request:
    types: [labeled]

jobs:
  deploy-backend:
    if: github.event.label.name == 'deploy_backend'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      service: conductor-backend
      image-name: backend
      build-context: conductor-backend/
      cloudrun-secrets: |
        DATABASE_URL=DATABASE_URL:latest
        DATABASE_USERNAME=DATABASE_USERNAME:latest
        DATABASE_PASSWORD=DATABASE_PASSWORD:latest
        APP_JWT_SECRET=APP_JWT_SECRET:latest
        FIREBASE_SERVICE_ACCOUNT_KEY=FIREBASE_SERVICE_ACCOUNT_KEY:latest
        RESEND_API_KEY=RESEND_API_KEY:latest
        GCP_SERVICE_ACCOUNT_KEY=GCP_SERVICE_ACCOUNT_KEY:latest
        GCP_STORAGE_BUCKET_NAME=GCP_STORAGE_BUCKET_NAME:latest
        FRONTEND_URL=FRONTEND_URL:latest
        WORKFLOW_SECRETS_KEY=WORKFLOW_SECRETS_KEY:latest
    secrets: inherit

  deploy-frontend:
    if: github.event.label.name == 'deploy_ui'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      service: conductor-frontend
      image-name: frontend
      build-context: conductor-frontend/
      is-frontend: true
      cloudrun-flags: --allow-unauthenticated
    secrets: inherit
